package ProgettoSettimanale;
//CREIAMO UN'INTERFACCIA PER TUTTI GLI ELEMENTI RIPRODUCIBILI (AUDIO O VIDEO)
public interface Riproduci {
	//DEFINIAMO UN METODO PLAY
	public void play();
	//DEFINIAMO UN METODO PER ALZARE ED ABBASSARE IL VOLUME IN QUANTO TUTTI GLI ELEMENTI RIPRODUCIBILI DISPONGONO DI TALI FUNZIONI
	public void volUp();
	public void volDown();
	
}
