package ProgettoSettimanale;
//CREIAMO UN'INTERFACCIA PER OGNI ELEMENTO VISUALIZZABILE (IMG, VIDEO)
public interface Visualizza {
	//DEFINIAMO UN METODO SHOW() CHE NEL CASO DELLE IMMAGINI CE LE MOSTRERà IN CONSOLE, NEL CASO DEI VIDEO MOSTRERà I DETTAGLI
	
	//DEFINIAMO DEI METODI PER GESTIRE LA LUMINOSITà DEGLI ELEMENTI MULTIMEDIALI
	public void AumentaL();
	public void DiminuisciL();
}
